name: NOMBRE_PIPELINE
# CUANDO_SE_EJECUTA_EL_PIPELINE(trigger)
on: push
    # pull_request:
    #         SE EJECUTA CUANDO SE CREA UN pull_request
    #       Ejecuto proceso automatizados para validar el PR (por ej, sonarq, correr el feature automatizado, etc)

    # push:
    #   branch: "NOMBRE_BRANCH"
    #         SE EJECUTA CUANDO SE MERGEA DENTRO DE UN BRANCH CON EL NOMBRE NOMBRE_BRANCH
    #       Ejecuto la regresion de pruebas, a nivel funcional para validar toda la aplicacion

jobs:
# las tareas que se van a ejecutar de manera automatizada
  my-job:
    runs-on: ubuntu-latest
    # En que entorno va a correr (sistema operativo)
    steps:
      - uses: actions/checkout@v3
        name: PASO1
        run: echo "Hello World!"